const API=process.env.NEXT_PUBLIC_API_BASE_URL||"http://localhost:8000";
async function getJSON(path,fallback){try{const r=await fetch(API+path,{cache:"no-store"});return r.ok?await r.json():fallback}catch{return fallback}}
export default async function Home(){
 const [s,incidents,services]=await Promise.all([
  getJSON("/api/dashboard/summary",{services:5,healthy_services:4,open_incidents:2,critical_incidents:1,avg_latency_ms:172,sla_compliance:99.31}),
  getJSON("/api/incidents",demoIncidents),getJSON("/api/services",demoServices)]);
 return <div className="shell"><aside className="sidebar"><div className="brand">CloudOps <span>AI</span></div><div className="muted">Operations Intelligence</div><nav className="nav"><div className="active">Overview</div><div>Services</div><div>Incidents</div><div>AI Intelligence</div><div>SLA & Reliability</div><div>Audit Log</div></nav></aside><main className="main"><div className="top"><div><div className="eyebrow">Platform overview</div><h1 className="title">Cloud operations control center</h1><div className="muted">Monitor services, investigate incidents and surface operational risk.</div></div><div className="badge">● Platform operational</div></div><section className="grid"><Metric label="Services" value={s.services} sub={s.healthy_services+" healthy"}/><Metric label="Open incidents" value={s.open_incidents} sub={s.critical_incidents+" critical"}/><Metric label="Avg. latency" value={s.avg_latency_ms+" ms"} sub="Across services"/><Metric label="SLA compliance" value={s.sla_compliance+"%"} sub="Rolling view"/></section><div className="hero"><div className="eyebrow">AI incident intelligence</div><h3>Prioritize what matters before customer impact expands.</h3><div className="muted">CloudOps AI generates concise incident summaries and correlates service health.</div></div><section className="two"><div className="card"><h2 className="section-title">Recent incidents</h2>{incidents.map(i=><div className="incident" key={i.id}><strong>{i.title}</strong><span className="muted">{i.service_name}</span><span className={"pill "+i.severity}>{i.severity}</span><span>{i.status}</span></div>)}</div><div className="card"><h2 className="section-title">Service health</h2>{services.map(x=><div className="service" key={x.id}><div><strong>{x.name}</strong><div className="muted">{x.owner} • {x.latency_ms} ms</div></div><div className="status">{x.status}</div></div>)}</div></section><div className="footer">Asad Hussain • Azure-ready cloud engineering portfolio</div></main></div>}
function Metric({label,value,sub}){return <div className="card"><div className="metric-label">{label}</div><div className="metric-value">{value}</div><div className="metric-sub">{sub}</div></div>}
const demoIncidents=[{id:1,title:"Payment gateway timeouts",service_name:"Checkout API",severity:"critical",status:"investigating"},{id:2,title:"Email delivery backlog",service_name:"Notification Worker",severity:"high",status:"mitigating"}];
const demoServices=[{id:1,name:"Checkout API",owner:"Commerce",latency_ms:118,status:"healthy"},{id:2,name:"Notification Worker",owner:"Messaging",latency_ms:412,status:"degraded"}];
